/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package applications.rest;
import java.sql.Date;
import java.sql.*;
import java.util.*;
import spark.*;
import static spark.Spark.*;
import com.google.gson.Gson;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.nio.charset.StandardCharsets;
import java.math.BigInteger;

public class App {

    public static void main(String[] args) {
        Database db = new Database("movies.db");
        port(7007);

        get("/ping", (req, res) -> db.getPing(res));
        post("/reset", (req, res) -> db.resetTable(req, res));
		post("/performances", (req, res) -> db.addPerformance(req, res));
		post("/tickets", (req, res) -> db.addTicket(req, res));
		get("/movies", (req, res)-> db.getMovies(req, res));
		get("/performances", (req, res) -> db.getPerformances(req, res));
		get("/movies/:imdb-key", (req, res) -> db.getMovie(req, res, req.params(":imdb-key")));
		get("/customers/:username/tickets", (req, res) -> db.getCustomer(req, res, req.params(":username")));
    }
}


class Database {
    /**
     * The database connection.
     */
    private Connection conn;
    private PasswordHashGenerator passGen;	

    /**
     * Creates the database interface object. Connection to the
     * database is performed later.
     */
    public Database(String filename) {
        openConnection(filename);
    }

    /**
     * Opens a connection to the database, using the specified
     * filename (if we'd used a traditional DBMS, such as PostgreSQL
     * or MariaDB, we would have specified username and password
     * instead).
     */
    public boolean openConnection(String filename) {
        try {
            Class.forName("org.sqlite.JDBC");
            conn = DriverManager.getConnection("jdbc:sqlite:" + filename);
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
            return false;
        }
        return true;
    }

    /**
     * Closes the connection to the database.
     */
    public void closeConnection() {
        try {
            if (conn != null) {
                conn.close();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * Checks if the connection to the database has been established
     * 
     * @return true if the connection has been established
     */
    public boolean isConnected() {
        return conn != null;
    }

	/* ================================== */
	/* --- insert your own code below --- */
	/* ===============================*== */

	


	public String getPing(Response res) {
		res.status(200);
		return "pong\n";
	}
	public String resetTable(Request req, Response res) {

		
		res.type("application/json");
		

		String query = "DELETE FROM movies";  

		 try (PreparedStatement ps = conn.prepareStatement(query)) {
			ps.executeUpdate();

		} catch (SQLException e) {
		    e.printStackTrace();
		return "caught";
		}
	

		query = "DELETE FROM customers";
		try (PreparedStatement ps = conn.prepareStatement(query)) {
			ps.executeUpdate();

		} catch (SQLException e) {
		    e.printStackTrace();
		return "caught";
		}
	
	
		query = "DELETE FROM theaters";

		try (PreparedStatement ps = conn.prepareStatement(query)) {
			ps.executeUpdate();

		} catch (SQLException e) {
		    e.printStackTrace();
		return "caught";
		}

		query = "DELETE FROM tickets";

		try (PreparedStatement ps = conn.prepareStatement(query)) {
			ps.executeUpdate();
		} catch (SQLException e) {
		    e.printStackTrace();
		return "caught";
		}

		query = "DELETE FROM screenings";

		try (PreparedStatement ps = conn.prepareStatement(query)) {
			ps.executeUpdate();
		} catch (SQLException e) {
		    e.printStackTrace();
		return "caught";
		}

		newCustomer("alice", "Alice", passGen.hash("dobido"));
		newCustomer("bob", "Bob", passGen.hash("whatsinaname"));
		newMovie("tt5580390", "The Shape of Water", 2016, 135);
		newMovie("tt4975722", "Moonlight", 2016, 111);
		newMovie("tt1895587", "Spotlight", 2015, 120);
		newMovie("tt2562232", "Birdman", 2014, 132);
		newTheater("Kino", 10);
		newTheater("Södran", 16);
		newTheater("Skandia", 100);
	
		res.body("ok");
		res.status(200);
		return "OK";
	}
	
	private boolean newCustomer(String user_name, String full_name, String pass_word)
	{
		String queryCustomers =
		"INSERT INTO customers (user_name, full_name, pass_word)\n" +
		"VALUES  (?, ?, ?)\n";
		try{
		PreparedStatement cust = conn.prepareStatement(queryCustomers);
		cust.setString(1, user_name);
		cust.setString(2, full_name);
		cust.setString(3, pass_word);
		cust.executeUpdate();
		return true;
		}catch(SQLException e){
			e.printStackTrace();
			return false;
		}
	}
	private boolean newMovie(String imdb_key, String movie_name, int production_year, int playtime)
	{
		String queryMovies =
		"INSERT INTO movies(imdb_key, movie_name, production_year, playtime)\n" +
		"VALUES (?,?,?,?)";
		try{PreparedStatement movie = conn.prepareStatement(queryMovies);
		movie.setString(1, imdb_key);
		movie.setString(2, movie_name);
		movie.setInt(3, production_year);
		movie.setInt(4, playtime);
		movie.executeUpdate();
		return true;
		}catch(SQLException e){
			e.printStackTrace();
			return false;
		}
	}
	private boolean newTheater(String theater_name, int capacity){
		String queryTheaters = 
		"INSERT INTO theaters(theater_name, capacity)\n" +
		"VALUES (?,?)";
		try{
			PreparedStatement theater = conn.prepareStatement(queryTheaters);
			theater.setString(1, theater_name);
			theater.setInt(2, capacity);
			theater.executeUpdate();
			return true;
		}catch(SQLException e){
			e.printStackTrace();
			return false;
		}
	}

public String getMovie (Request req, Response res, String imdb_key) {
	res.type("application/json");
	String query = 
		"SELECT imdb_key AS imdbKey, movie_name AS name, production_year AS year\n" + 
		"FROM movies\n" +
		"WHERE imdbKey = ?\n";

	try (PreparedStatement ps = conn.prepareStatement(query)) {
        ps.setString(1, imdb_key);
    	ResultSet rs = ps.executeQuery();
        String result = JSONizer.toJSON(rs, "data");
        res.status(200);
        res.body(result);
        return result;
    } catch (SQLException e) {
        e.printStackTrace();
    }
    
	return "";
}

public String getCustomer (Request req, Response res, String username) {
	res.type("application/json");
	String query = 
		"SELECT screening_date AS date, screening_time AS time," + 
			"theater_name AS theater, movie_name AS title," + 
			"production_year AS year, count() AS nbrOfTickets\n" +
		"FROM tickets\n" +
		"JOIN screenings\n" +
		"USING (screening_date, screening_time, theater_name)\n" +
		"WHERE user_name = ?\n" + 
		"GROUP BY screening_id\n";

	try (PreparedStatement ps = conn.prepareStatement(query)) {
            ps.setString(1, username);
            ResultSet rs = ps.executeQuery();
            String result = JSONizer.toJSON(rs, "data");
            res.status(200);
            res.body(result);
            return result;
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return "";
}
public String addTicket (Request req, Response res){
	int remaining_seats = 0;
	String screening_time = "";
	String screening_date = "";
	String theater_name  = "";
	String ticketID = "tes";
	String queryFindRemaningSeats =
	"SELECT remaining_seats, screening_time, screening_date, theater_name\n" +
	"FROM screenings\n" +
	"WHERE screening_id = ?";
	try(PreparedStatement ps = conn.prepareStatement(queryFindRemaningSeats)){
		ps.setString(1, req.queryParams("performance"));
		ResultSet rs = ps.executeQuery();
		remaining_seats = rs.getInt(1);
		screening_time = rs.getString(2);
		screening_date = rs.getString(3);
		theater_name = rs.getString(4);
	}catch(SQLException e){
		e.printStackTrace();
		return "Error";
	}
	if(remaining_seats <= 0)
	{
		return "No tickets left";
	}
	String queryPassword =
	"SELECT pass_word\n" +
	"FROM customers\n" +
	"WHERE user_name = ?";
	try{
		PreparedStatement ps = conn.prepareStatement(queryPassword);
		ps.setString(1, req.queryParams("user"));
		ResultSet rs = ps.executeQuery();	
		if(!rs.getString(1).equals(passGen.hash(req.queryParams("pwd")))){
			return "Wrong password";
		}
	}catch(SQLException e){
		e.printStackTrace();
		return "Error";
	}
	String queryTicket =
	"INSERT INTO tickets (user_name, screening_time, screening_date, theater_name)\n" +
		"VALUES  (?, ?, ?, ?)\n";

	try (PreparedStatement ps = conn.prepareStatement(queryTicket)) {
            ps.setString(1, req.queryParams("user"));
			ps.setString(2, screening_time);
			ps.setString(3, screening_date);
			ps.setString(4, theater_name);
			ps.executeUpdate();
	}
	catch(SQLException e){
		e.printStackTrace();
		return "Error";
	}


	String queryUpdate =
	"UPDATE screenings \n" + 
	"SET remaining_seats = ?\n" + 
	"WHERE screening_id = ?";

	 try (PreparedStatement ps = conn.prepareStatement(queryUpdate)) {
		 	remaining_seats --;
            ps.setInt(1, remaining_seats);
			ps.setString(2, req.queryParams("performance"));
			ps.executeUpdate();
	}
	catch(SQLException e){
		e.printStackTrace();
		return "ErrorInsert";
	}
	String queryFindId = 
		"SELECT ticket_id\n" + 
		"FROM tickets\n" +
		"WHERE rowid = last_insert_rowid()";
		try (PreparedStatement ps2 = conn.prepareStatement(queryFindId)) {
			ResultSet rs = ps2.executeQuery();
			ticketID = rs.getString(1);
		}
		catch(SQLException e){
		e.printStackTrace();
	return "caught3";
	}
		return "/ticket/" + ticketID;

}
public String addPerformance (Request req, Response res) {
	String performanceID = "error";
	String title = "test";
	int capacity_new = 0;
	int year = 666;
	res.type("application/json");
	String queryPerformance = 
		"INSERT INTO screenings (screening_time, screening_date, production_year, movie_name, theater_name, remaining_seats)\n" +
		"VALUES (?,?,?,?,?,?)";
	String queryFind = 
		"SELECT production_year, movie_name \n" +
		"FROM movies\n" +
		"WHERE imdb_key = ?";
	String queryFindTheater =
		"SELECT capacity\n" +
		"FROM theaters\n" +
		"WHERE theater_name = ?";

	try (PreparedStatement ps = conn.prepareStatement(queryFind)) {
		ps.setString(1, req.queryParams("imdb"));
		ResultSet rs = ps.executeQuery();
		year = rs.getInt(1);
		title = rs.getString(2);
	}
	catch(SQLException e){
		e.printStackTrace();
	return "No such movie or theater";
	}
	try (PreparedStatement ps = conn.prepareStatement(queryFindTheater)) {
		ps.setString(1, req.queryParams("theater"));
		ResultSet rs = ps.executeQuery();
		capacity_new = rs.getInt(1);
	}
	catch(SQLException e){
		e.printStackTrace();
	return "No such movie or theater";
	}
	
	try (PreparedStatement ps = conn.prepareStatement(queryPerformance)) {
		ps.setString(1, req.queryParams("time"));
		ps.setString(2, req.queryParams("date"));
		ps.setInt(3, year);
		ps.setString(4, title);
		ps.setString(5, req.queryParams("theater"));
		ps.setInt(6, capacity_new);
		ps.executeUpdate();
	}	
	catch(SQLException e){
		e.printStackTrace();
	return "#369_multiple_error?";
	}
	String queryFindId = 
		"SELECT screening_id \n" +
		"FROM screenings\n" +
		"WHERE theater_name = ? AND screening_date = ? AND screening_time = ?";
		try (PreparedStatement ps2 = conn.prepareStatement(queryFindId)) {
			ps2.setString(1, req.queryParams("theater"));
			ps2.setString(2, req.queryParams("date"));
			ps2.setString(3, req.queryParams("time"));
			ResultSet rs = ps2.executeQuery();
			performanceID = rs.getString(1);
		}
		catch(SQLException e){
		e.printStackTrace();
	return "caught3";
	}
		return "/performances/" + performanceID;
}

public String getPerformances (Request req, Response res) {

res.type("application/json");
String query = 
	"SELECT *\n" +
	"FROM screenings\n";

try (PreparedStatement ps = conn.prepareStatement(query)) {
	ResultSet rs = ps.executeQuery();
        String result = JSONizer.toJSON(rs, "data");
        res.status(200);
        res.body(result);
        return result;
        } catch (SQLException e) {
            e.printStackTrace();
        }
	return "OK \n";
}

public String getMovies(Request req, Response res){
	if(req.queryParams().size() == 2){	
			String title = req.queryParams("title");
			int year = Integer.parseInt(req.queryParams("year"));
			String query = "SELECT imdb_key AS imdbKey, movie_name AS title, production_year AS year \n" +			
			"FROM movies \n" +
			"WHERE movie_name = ? AND production_year = ? \n";
			
		try (PreparedStatement ps = conn.prepareStatement(query)) {

		ps.setString(1, title);
		ps.setInt(2, year);
		ResultSet rs = ps.executeQuery();
		String result = JSONizer.toJSON(rs, "data");
		res.status(200);
		res.body(result);
		return result;
		}
	catch (SQLException e) {
	e.printStackTrace();
	return query;

	}
	}
else{
	res.type("application/json");
	String query = "SELECT imdb_key AS imdbKey, movie_name AS title, production_year AS year \n" +
	"FROM movies \n";
	try{
	PreparedStatement ps = conn.prepareStatement(query);
	ResultSet rs = ps.executeQuery();
	String result = JSONizer.toJSON(rs, "data");
	res.status(200);
	res.body(result);
	return result;
	
	}catch(SQLException e){
	e.printStackTrace();
	}
	return "";
}}

}
/**
 * Auxiliary class for automatically translating a ResultSet to JSON
 */
class PasswordHashGenerator {

    public static String hash(String text) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            md.update(text.getBytes(StandardCharsets.UTF_8));
            byte[] digest = md.digest();
            return String.format("%064x", new BigInteger(1, digest));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}

class JSONizer {

    public static String toJSON(ResultSet rs, String name) throws SQLException {
        StringBuilder sb = new StringBuilder();
        ResultSetMetaData meta = rs.getMetaData();
        boolean first = true;
        sb.append("{\n");
        sb.append("  \"" + name + "\": [\n");
        while (rs.next()) {
            if (!first) {
                sb.append(",");
                sb.append("\n");
            }
            first = false;
            sb.append("    {");
            for (int i = 1; i <= meta.getColumnCount(); i++) {
                String label = meta.getColumnLabel(i);
                String value = getValue(rs, i, meta.getColumnType(i));
                sb.append("\"" + label + "\": " + value);
                if (i < meta.getColumnCount()) {
                    sb.append(", ");
                }
            }
            sb.append("}");
        }
        sb.append("\n");
        sb.append("  ]\n");
        sb.append("}\n");
        return sb.toString();
    }
	
    private static String getValue(ResultSet rs, int i, int columnType) throws SQLException {
        switch (columnType) {
        case java.sql.Types.INTEGER:
            return String.valueOf(rs.getInt(i));
        case java.sql.Types.REAL:
        case java.sql.Types.DOUBLE:
        case java.sql.Types.FLOAT:
            return String.valueOf(rs.getDouble(i));
        default:
            return "\"" + rs.getString(i) + "\"";
        }
    }
}
